# Generated by Django 4.2.28 on 2026-03-31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome do Produto")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Descrição")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Preço")),
                (
                    "shipping_type",
                    models.CharField(
                        choices=[
                            ("leve", "Leve"),
                            ("medio", "Médio"),
                            ("meio-pesado", "Meio-Pesado"),
                            ("pesado", "Pesado"),
                        ],
                        default="medio",
                        max_length=20,
                        verbose_name="Tipo de Envio",
                    ),
                ),
                ("photo", models.ImageField(blank=True, null=True, upload_to="items/", verbose_name="Foto")),
                ("is_for_sale", models.BooleanField(default=True, verbose_name="À Venda")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "company"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
                "db_table": "items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TechnicalVisitRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("preferred_date", models.DateField(blank=True, null=True)),
                ("address", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("accepted", "Aceito"),
                            ("refused", "Recusado"),
                            ("completed", "Concluído"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consumer",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "consumer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technical_visit_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "provider"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technical_visit_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "technical_visit_requests", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_entries",
                        to="core.item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "cart_items", "ordering": ["-updated_at"], "unique_together": {("user", "item")}},
        ),
    ]
