# Generated by Django 4.2.28 on 2026-05-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_pending_since"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="marca",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="Marca"),
        ),
    ]
