from django.urls import path
from .views import (
    CartItemDetailView,
    CartItemListCreateView,
    DelivererDetailView,
    DelivererListCreateView,
    health_check,
    readiness_check,
    featured_stores,
    nearby_providers,
    stores_for_provider,
    PublicItemListView,
    ItemListCreateView,
    ItemDetailView,
    create_technical_visit,
    my_visits,
    visit_detail,
    cancel_visit,
    complete_visit,
    provider_visit_panel,
    update_visit_status,
    visit_messages,
    create_review,
    list_reviews,
    admin_stats,
    admin_providers_list,
    admin_stores_list,
    create_order,
    my_orders,
    company_orders,
    order_detail,
    update_order_status,
    order_messages,
    order_stats,
    bills_list_create,
    bill_detail,
    inventory_list_create,
    inventory_detail,
    store_detail,
    cart_shipping_estimate,
)

app_name = "core"

urlpatterns = [
    path("health/", health_check, name="health"),
    path("ready/", readiness_check, name="readiness"),
    path("stores/featured/", featured_stores, name="featured_stores"),
    path("providers/nearby/", nearby_providers, name="nearby_providers"),
    path("stores/provider/", stores_for_provider, name="stores_for_provider"),
    path("items/public/", PublicItemListView.as_view(), name="public_item_list"),
    path("items/", ItemListCreateView.as_view(), name="item_list_create"),
    path("items/<int:pk>/", ItemDetailView.as_view(), name="item_detail"),
    path("cart/", CartItemListCreateView.as_view(), name="cart_list_create"),
    path("cart/<int:pk>/", CartItemDetailView.as_view(), name="cart_detail"),
    path("cart/shipping-estimate/", cart_shipping_estimate, name="cart_shipping_estimate"),
    path("deliverers/", DelivererListCreateView.as_view(), name="deliverer_list_create"),
    path("deliverers/<int:pk>/", DelivererDetailView.as_view(), name="deliverer_detail"),
    path("technical-visits/", create_technical_visit, name="technical_visit_create"),
    path("technical-visits/my/", my_visits, name="my_visits"),
    path("technical-visits/provider-panel/", provider_visit_panel, name="technical_visit_provider_panel"),
    path("technical-visits/<int:visit_id>/", visit_detail, name="visit_detail"),
    path("technical-visits/<int:visit_id>/update/", update_visit_status, name="technical_visit_update"),
    path("technical-visits/<int:visit_id>/cancel/", cancel_visit, name="cancel_visit"),
    path("technical-visits/<int:visit_id>/complete/", complete_visit, name="complete_visit"),
    path("technical-visits/<int:visit_id>/messages/", visit_messages, name="visit_messages"),
    path("reviews/", create_review, name="create_review"),
    path("reviews/list/", list_reviews, name="list_reviews"),
    path("admin/stats/", admin_stats, name="admin_stats"),
    path("admin/providers/", admin_providers_list, name="admin_providers_list"),
    path("admin/stores/", admin_stores_list, name="admin_stores_list"),
    # Orders
    path("orders/", create_order, name="create_order"),
    path("orders/my/", my_orders, name="my_orders"),
    path("orders/company/", company_orders, name="company_orders"),
    path("orders/stats/", order_stats, name="order_stats"),
    path("orders/<int:order_id>/", order_detail, name="order_detail"),
    path("orders/<int:order_id>/status/", update_order_status, name="update_order_status"),
    path("orders/<int:order_id>/messages/", order_messages, name="order_messages"),
    # Bills
    path("bills/", bills_list_create, name="bills_list_create"),
    path("bills/<int:bill_id>/", bill_detail, name="bill_detail"),
    # Inventory
    path("inventory/", inventory_list_create, name="inventory_list_create"),
    path("inventory/<int:entry_id>/", inventory_detail, name="inventory_detail"),
    # Store profile
    path("stores/<int:store_id>/", store_detail, name="store_detail"),
]
