# Generated by Django 4.2.28 on 2026-03-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_user_email_provider_passwordresettoken_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="avg_minutes_per_km",
            field=models.DecimalField(decimal_places=2, default=4, max_digits=5),
        ),
        migrations.AddField(
            model_name="company",
            name="closing_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="display_radius_km",
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
        migrations.AddField(
            model_name="company",
            name="onboarding_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="company",
            name="opening_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="rating_average",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="company",
            name="rating_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="provider",
            name="rating_average",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="provider",
            name="rating_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
