# Generated by Django 4.2.28 on 2026-05-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_add_photo_coverage_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="pix_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="company",
            name="pix_key_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cpf", "CPF"),
                    ("cnpj", "CNPJ"),
                    ("email", "E-mail"),
                    ("telefone", "Telefone"),
                    ("aleatoria", "Chave Aleatória"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
